
name: Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@v5
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

