
name: Many jobs
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@v5
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@v5
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@v5
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."

