
name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: action/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test

